"""empty message

Revision ID: 642390c66799
Revises: 65ad1076b7d4
Create Date: 2016-12-22 15:33:15.668639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642390c66799'
down_revision = '65ad1076b7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ping', sa.Column('received_num', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ping', 'received_num')
    # ### end Alembic commands ###
