"""empty message

Revision ID: 85de5ba469ad
Revises: 8ba49db425f0
Create Date: 2016-12-22 16:08:24.180931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85de5ba469ad'
down_revision = '8ba49db425f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('participant', 'p_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('p_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('participant', 'name')
    # ### end Alembic commands ###
