"""empty message

Revision ID: 8ba49db425f0
Revises: c9159994174b
Create Date: 2016-12-22 16:01:32.520452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba49db425f0'
down_revision = 'c9159994174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('p_name', sa.String(), nullable=True))
    op.drop_column('participant', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('participant', 'p_name')
    # ### end Alembic commands ###
