"""empty message

Revision ID: a77b25f636e0
Revises: 85de5ba469ad
Create Date: 2016-12-22 16:12:06.834049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77b25f636e0'
down_revision = '85de5ba469ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'phone_number')
    # ### end Alembic commands ###
