"""empty message

Revision ID: c9159994174b
Revises: 642390c66799
Create Date: 2016-12-22 15:43:03.028156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9159994174b'
down_revision = '642390c66799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('survey_type', sa.String(), nullable=True))
    op.drop_column('survey', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('survey', 'survey_type')
    # ### end Alembic commands ###
