"""empty message

Revision ID: d6b87e714c6e
Revises: a77b25f636e0
Create Date: 2016-12-22 16:24:41.987988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b87e714c6e'
down_revision = 'a77b25f636e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'survey', ['survey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'survey_id')
    # ### end Alembic commands ###
