"""empty message

Revision ID: d71bd1c9f887
Revises: d6b87e714c6e
Create Date: 2016-12-22 17:04:36.345635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd71bd1c9f887'
down_revision = 'd6b87e714c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('body', postgresql.JSON))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'body')
    # ### end Alembic commands ###
